### ISSUE TITLE
Admin EPIC

### ISSUE THREAD

**Issue by birgerosterberg** [birgerosterberg/thebazaar#10]
#### **Description**
As an admin, I need to oversee and manage all orders placed on the website, with functionalities to view, filter, and access order details.

#### **Tasks**
- [x] Implement viewing of all orders placed, grouped by date.
- [x] Enable filtering of orders by date.
- [x] Allow access to full details of every order.
