### ISSUE TITLE
Contact EPIC

### ISSUE THREAD

**Issue by birgerosterberg** [birgerosterberg/thebazaar#13]
#### **Description**
As a user, I need to easily find and use the contact page, accessing essential information and contacting Sanda Bazaar when needed.

#### **Tasks**
- [x] Ensure easy navigation to the contact page.
- [x] Display the bazaar's location, opening hours, and contact details.
- [x] Integrate a Google map for the bazaar
