### ISSUE TITLE
USER STORY: Project Setup #2

### ISSUE THREAD

**Issue by birgerosterberg** [birgerosterberg/thebazaar#14]
As a developer, I can set up Django and deploy the site so that I can ensure that the ground works are done.

### Tasks

- [x] Set up Django 
- [x] Test Run Django so it works
- [x] Create GitHub workspace
- [x] Install & Setup AllAuth
