### ISSUE TITLE
Blog EPIC

### ISSUE THREAD

**Issue by birgerosterberg** [birgerosterberg/thebazaar#19]
#### **Description**
As a user, I want to explore engaging and visually appealing blog content related to Sanda Bazaar.

#### **Tasks**
- [x] Ensure easy finding and access to the blog page.
- [x] Create diverse and engaging blog posts.
- [x] Develop visually appealing blog posts with images or videos.
