### ISSUE TITLE
Viewing and Navigation EPIC

### ISSUE THREAD

**Issue by birgerosterberg** [birgerosterberg/thebazaar#2]
#### **Description**
As a user, I need a website that is easy to understand, navigate, and use across different devices, ensuring all features are accessible and the site's purpose is clear from the first interaction.

#### **Tasks**
- [x] Ensure clarity of website's purpose on the homepage.
- [x] Test and improve site functionalities across various viewports.
- [x] Design and implement a comprehensive footer with relevant information.
- [x] Ensure continuous accessibility of the navigation menu.
- [x] Implement and test keyword search functionality for site products.
