### ISSUE TITLE
Reviews EPIC

### ISSUE THREAD

**Issue by birgerosterberg** [birgerosterberg/thebazaar#5]
#### **Description**
As a user, I want to view, add, and understand product reviews to make informed purchase decisions.

#### **Tasks**
- [x] Enable viewing of all reviews for each product.
- [x] Allow logged-in users to add reviews for purchased products.
- [x] Implement functionality to display a general product rating.
