### ISSUE TITLE
Bag EPIC

### ISSUE THREAD

**Issue by birgerosterberg** [birgerosterberg/thebazaar#7]
#### **Description**
As a user, I want to manage products in my shopping bag, including viewing, adding, removing, and adjusting quantities.

#### **Tasks**
- [x] Enable users to view all products in the shopping bag.
- [x] Allow adding/removing of products from the shopping bag.
- [x] Display detailed price information for the order.
- [x] Provide functionality to edit product quantities in the bag.
