### ISSUE TITLE
Checkout EPIC

### ISSUE THREAD

**Issue by birgerosterberg** [birgerosterberg/thebazaar#8]
#### **Description**
As a user, I want a seamless checkout process, from viewing and editing delivery details to completing payment for my order.

#### **Tasks**
- [x] Enable editing of default delivery details for logged-in users.
- [x] Implement display of order summary with price details.
- [x] Allow adding of delivery details for the order.
- [x] Integrate a system for inputting card details for payment.
