### ISSUE TITLE
User Profile EPIC

### ISSUE THREAD

**Issue by birgerosterberg** [birgerosterberg/thebazaar#9]
#### **Description**
As a logged-in user, I want to view and edit my personal and order details, maintaining an up-to-date and accessible profile.

#### **Tasks**
- [x] Allow users to view and edit their delivery details.
- [x] Enable users to view their order history.
- [x] Provide access to full details of each placed order.
